CREATE SCHEMA biblioteca AUTHORIZATION tldesafio;

CREATE TABLE biblioteca.usuario (
	id int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE),
	nome varchar(255) NULL,
	perfil_usuario varchar(255) NULL,
	senha varchar(255) NULL,
	CONSTRAINT ukplwlwihgql09syg15ux4p1kgo UNIQUE (nome),
	CONSTRAINT usuario_perfil_usuario_check CHECK (((perfil_usuario)::text = ANY ((ARRAY['ADMINISTRADOR'::character varying, 'CLIENTE'::character varying])::text[]))),
	CONSTRAINT usuario_pkey PRIMARY KEY (id)
);

-- biblioteca.livro definition

-- Drop table

-- DROP TABLE biblioteca.livro;

CREATE TABLE biblioteca.livro (
	id int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE),
	author varchar(255) NULL,
	created_at timestamp(6) NULL,
	nome varchar(255) NULL,
	usuario_id int4 NULL,
	CONSTRAINT livro_pkey PRIMARY KEY (id)
);


-- biblioteca.livro foreign keys

ALTER TABLE biblioteca.livro ADD CONSTRAINT fkjbrg4ntd95dhod10dp5vihxhq FOREIGN KEY (usuario_id) REFERENCES biblioteca.usuario(id);

INSERT INTO biblioteca.usuario(id, nome, perfil_usuario, senha)VALUES(1, 'admin', 'ADMINISTRADOR', '202cb962ac59075b964b07152d234b70');

INSERT INTO biblioteca.livro(id, author, created_at, nome, usuario_id)VALUES(1000, 'Deitel', '2024-05-30 14:46:56.161', 'Java Como programar', 1);
INSERT INTO biblioteca.livro(id, author, created_at, nome, usuario_id)VALUES(20000, 'Marting Fowler', '2024-05-30 14:48:26.211', 'Arquitetura Limpa', 1);
INSERT INTO biblioteca.livro(id, author, created_at, nome, usuario_id)VALUES(30000, 'Erick Evans', '2024-05-30 14:48:40.413', 'Domain Driven Design', 1);
INSERT INTO biblioteca.livro(id, author, created_at, nome, usuario_id)VALUES(5000, 'Casa do código', '2024-05-30 15:02:06.553', 'Vire o Jogo com Spring Framework ', 1);
INSERT INTO biblioteca.livro(id, author, created_at, nome, usuario_id)VALUES(6000, 'Casa do código', '2024-05-30 15:02:06.553', 'Aprenda a programar com Python', 1);
INSERT INTO biblioteca.livro(id, author, created_at, nome, usuario_id)VALUES(7000, 'Casa do código', '2024-05-30 15:02:06.553', 'Kit robótico LEGO® EV3.', 1);
INSERT INTO biblioteca.livro(id, author, created_at, nome, usuario_id)VALUES(8000, 'Casa do código', '2024-05-30 15:02:06.553', 'Kodular', 1);
INSERT INTO biblioteca.livro(id, author, created_at, nome, usuario_id)VALUES(9000, 'Casa do código', '2024-05-30 15:02:06.553', 'Construct 2.', 1);
